### ISSUE TITLE
error when updating template.js

### ISSUE THREAD

**Issue by bastipnt** [bgola/ffglitch-livecoding#1]
When trying to update the `template.js` file while running the livecoding server I get following error on my mac M1:
```sh
pip run zmqserver_livecoding_watchdog.py template.js
Traceback (most recent call last):
  File "~/ffglitch-livecoding/zmqserver_livecoding_watchdog.py", line 97, in <module>
    start_zmq_server(checker)
    ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "~/ffglitch-livecoding/zmqserver_livecoding_watchdog.py", line 59, in start_zmq_server
    socket.send_string(last_code)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "~/ffglitch-livecoding/.venv/lib/python3.13/site-packages/zmq/sugar/socket.py", line 907, in send_string
    return self.send(u.encode(encoding), flags=flags, copy=copy, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/ffglitch-livecoding/.venv/lib/python3.13/site-packages/zmq/sugar/socket.py", line 701, in send
    return super().send(data, flags=flags, copy=copy, track=track)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "_zmq.py", line 1092, in zmq.backend.cython._zmq.Socket.send
  File "_zmq.py", line 1140, in zmq.backend.cython._zmq.Socket.send
  File "_zmq.py", line 1344, in zmq.backend.cython._zmq._send_copy
  File "_zmq.py", line 1339, in zmq.backend.cython._zmq._send_copy
  File "_zmq.py", line 179, in zmq.backend.cython._zmq._check_rc
zmq.error.ZMQError: Operation cannot be accomplished in current state
```

**Comment by bastipnt** [comment]
maybe this is related?
- https://stackoverflow.com/questions/41009900/python-zmq-operation-cannot-be-accomplished-in-current-state
- https://stackoverflow.com/questions/40423825/how-to-protect-zeromq-request-reply-pattern-against-potential-drops-of-messages/40429335#40429335

**Comment by bgola** [comment]
tks @bastipnt , this should be fixed now :)

I will close the issue, if it happens again feel free to open a new one.
